server:
    port: 8080
    servlet:
        context-path: /creative-teacher

spring:
    datasource:
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/creative_campus
            username: DinoStark
            password: non-feeling

logging:
    level: info
