server:
    port: 8080
    servlet:
        context-path: /creative-teacher

spring:
    datasource:
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/creative_campus
            username: DinoStark
            password: non-feeling
    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: 127.0.0.1
        jedis:
            pool:
                # 连接池最大连接数（使用负值表示没有限制）
                max-active: 20
                # 连接池中的最大空闲连接
                max-idle: 10
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
                # 连接池中的最小空闲连接
                min-idle: 0
        # Redis服务器连接密码（默认为空）
        password: ''
        # Redis服务器连接端口
        port: 6379
        # 连接超时时间（毫秒）
        timeout: 1000

logging:
    pattern:
        console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
        root: info

